import json

def transform(data):
    f = open("public/tutor_data.json", "w")
    f.write("[\n")
    for i in range(len(data)):
        student = data[i]
        student["mathcore"] = None if student["mathcore"] == "None" else student["mathcore"].split(", ")
        student["moreMath"] = None if student["moreMath"] == "None" else student["moreMath"].split(", ")
        student["cs"] = None if student["cs"] == "None" else student["cs"].split(", ")
        student["biology"] = None if student["biology"] == "None" else student["biology"].split(", ")
        student["chemistry"] = None if student["chemistry"] == "None" else student["chemistry"].split(", ")
        student["physics"] = None if student["physics"] == "None" else student["physics"].split(", ")
        student["language"] = None if student["language"] == "None" else student["language"].split(", ")
        student["otherScience"] = None if student["otherScience"] == "None" else student["otherScience"].split(", ")
        student["aboutMe"] = student.pop("aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences")
        del student["timestamp"]
        if "anyOtherCoursesNotListedAbove" in student:
            del student["anyOtherCoursesNotListedAbove"]
        f.write(json.dumps(student))
        f.write("," if i != len(data) - 1 else "")
        f.write("\n")
    f.write("]")


d = [
    {
        "timestamp": "2023-10-02T23:45:17.598Z",
        "emailAddress": "vyou@imsa.edu",
        "firstName": "Vincent",
        "lastName": "You",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi! My name's Vincent and I'm excited to help you with your courses. When I'm not studying for my next math test, I enjoy playing the saxophone and programming.",
        "mathcore": "MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I",
        "otherScience": "MSI",
        "id": 125236,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-02-01T18:03:46.804Z",
        "emailAddress": "zcai@imsa.edu",
        "firstName": "Zhuoer",
        "lastName": "Cai",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Zhuoer. I'm in discrete, BC 2, and number theory this semester",
        "mathcore": "MI II, MI III, MI IV, BC I",
        "moreMath": "None, Intro to Proofs",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125027,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T04:59:45.807Z",
        "emailAddress": "abrahmandam@imsa.edu",
        "firstName": "Arjun",
        "lastName": "Brahmandam ",
        "hall": 1505,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey guys! I’m a huge math, music, and ping pong nerd and will talk to anyone about anything (even something I don’t know of). I’m ambi/omniverted as well and have a hobby of listening to random convos besides me without being in the mood to engage in them, so I completely understand both sides of the spectrum. So feel free to ask me anything about that part as well, no matter who you are. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "Statistics",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "Spanish II, Spanish III",
        "otherScience": "None",
        "anyOtherCoursesNotListedAbove": "I can also tutor music theory if needed. ",
        "id": 125022,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T05:15:29.358Z",
        "emailAddress": "dleigh@imsa.edu",
        "firstName": "Dashiell",
        "lastName": "Leigh",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Dash (he/him). I'm a math nerd, I'm involved in Diversity, Equity, and Inclusion at IMSA, and I like taking long walks on the beach and looking pretentiously up at the stars while I listen to Radiohead. In all seriousness, I love music and dancing and just talking to people, and I'm always here to chat.",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "Differential Equations",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "Spanish II, Spanish III, Spanish IV, Spanish V",
        "otherScience": "Biophysics",
        "id": 124115,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-04T13:03:34.053Z",
        "emailAddress": "pcahill@imsa.edu",
        "firstName": "Patrick ",
        "lastName": "Cahill",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm happy to talk about anything, and you can contact me anytime ",
        "mathcore": "Geometry, MI II, MI III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "Nope ",
        "id": 125025,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T15:42:31.460Z",
        "emailAddress": "smehendale@imsa.edu",
        "firstName": "Shridhar",
        "lastName": "Mehendale",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Junior with a passion in math and business. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125136,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-04T19:53:47.236Z",
        "emailAddress": "wguo@imsa.edu",
        "firstName": "William",
        "lastName": "Guo",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Junior in 05 B Wing. Enjoys golf and sports.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125072,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-24T18:13:22.201Z",
        "emailAddress": "lbrower@imsa.edu",
        "firstName": "Lucas",
        "lastName": "Brower",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I love math but will help in any course I've been in. In my free time I play video games, basketball, or workout. ",
        "mathcore": "MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "Computational Science",
        "id": 124025,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-07T01:24:03.808Z",
        "emailAddress": "yyardi@imsa.edu",
        "firstName": "Yash",
        "lastName": "Yardi",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I enjoy working in computer science and math. In my free time I like to play sports and be outside, and when I am working I prefer the indoors where there are far less distractions and I can stay focused. ",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125298,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T02:11:30.983Z",
        "emailAddress": "mchen2@imsa.edu",
        "firstName": "Max",
        "lastName": "Chen",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I'm Max!",
        "mathcore": "None",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125033,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T04:07:28.605Z",
        "emailAddress": "pveeramachaneni@imsa.edu",
        "firstName": "Prabhav",
        "lastName": "Veeramachaneni",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi I'm Prabhav. I live in 1501 D wing and am a Junior. I enjoy video editing and am always eager to learn more. If you ever need help feel free to ask, I'll try my best.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125294,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T13:58:10.072Z",
        "emailAddress": "lbannon@imsa.edu",
        "firstName": "Sori",
        "lastName": "Bannon",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "IMSAs most obnoxious queer, unless you think you could do better. I tutor in CSI, WebTech, and OOP. You can find me in the hall commons 7:30-9 on Mondays, Tuesdays, and Thursdays.",
        "mathcore": "None",
        "moreMath": "None",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "anyOtherCoursesNotListedAbove": "Speculative Fiction",
        "id": 124016,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-16T14:39:22.890Z",
        "emailAddress": "dxianto@imsa.edu",
        "firstName": "Dylan",
        "lastName": "Xianto",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am Dylan, a tutor for 1501. I am very fond of science, especially chemistry.",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry, Advanced Chemistry, Environmental Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "MSI",
        "id": 125230,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T13:32:09.809Z",
        "emailAddress": "rmandell@imsa.edu",
        "firstName": "Bobby",
        "lastName": "Mandell",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi my name is Bobby. I love hockey, and I play left wing. I have great friends and an awesome quad. Feel free to come to me with any questions or if you just want to chat!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "None, SI Chemistry",
        "physics": "None, SI Physics, Modern Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "Mod Phys",
        "id": 125130,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-16T19:24:47.172Z",
        "emailAddress": "blamb1@imsa.edu",
        "firstName": "Bryan",
        "lastName": "Lamb",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Bryan, I'm a junior, and I really like being a peer tutor. I don't have one subject that I am the greatest at tutoring, but my favorite in general and to help with is physics. I look forward to helping where I can. ",
        "mathcore": "MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "German I, German II",
        "otherScience": "None",
        "id": 125114,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-17T00:25:16.754Z",
        "emailAddress": "ekemph@imsa.edu",
        "firstName": "Evan",
        "lastName": "Kemph",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am friendly, I don't bite! I like computers, engineering, and math. I am happy to help with any problem that I can.",
        "mathcore": "MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Mandarin I",
        "otherScience": "MSI",
        "id": 125102,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-17T22:31:10.403Z",
        "emailAddress": "dcano@imsa.edu",
        "firstName": "Daniel",
        "lastName": "Cano",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, my name is Dani. I love anime, videogames, cooking, and just about everything science. ",
        "mathcore": "MI I/II, MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "None",
        "language": "Mandarin I, Mandarin II",
        "otherScience": "None",
        "id": 124029,
        "graduationYear": 2024
    },
    {
        "timestamp": "2023-10-21T02:50:47.416Z",
        "emailAddress": "xalbertson@imsa.edu",
        "firstName": "Xander",
        "lastName": "Albertson",
        "hall": 1505,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Xander and I love to hang out with my friends and play all different media of games. Some of my favorites are Magic the Gathering, Marvel Villainous, and Super Smash Bros. If you’re looking for me you can probably find me in the gym because I also love to work out. My favorite food is barbecue chicken drumstick. I also have a crippling addiction to sleep.",
        "mathcore": "MI III, MI IV",
        "moreMath": "None",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125006,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-21T03:20:46.979Z",
        "emailAddress": "ichung@imsa.edu",
        "firstName": "Ian",
        "lastName": "Chung",
        "hall": 1501,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am a peer tutor",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125038,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-21T03:58:06.867Z",
        "emailAddress": "shattarki@imsa.edu",
        "firstName": "Shrishant",
        "lastName": "Hattarki",
        "hall": 1505,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I’m Shrishant, and I’m a junior in 05 C wing. I tutor anything math/cs related on Tuesdays, Wednesdays , and Thursdays.",
        "mathcore": "MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125080,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-22T21:48:21.850Z",
        "emailAddress": "ashah1@imsa.edu",
        "firstName": "Aaditya",
        "lastName": "Shah",
        "hall": 1505,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, my name is Aadi Shah, and I'm a junior and a peer tutor for 05. I like to spend my free time hanging out with friends, listening to music, and watching/playing sports.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI, Engineering",
        "id": 125188,
        "graduationYear": 2025
    },
    {
        "timestamp": "2023-10-23T01:04:34.717Z",
        "emailAddress": "njoseph1@imsa.edu",
        "firstName": "Noel",
        "lastName": "Skariah",
        "hall": 1501,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi name is Noel Skariah and I am interesting in music, dance, and helping others. I am interested in math and science and hope to become a doctor one day.",
        "mathcore": "MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125307,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T06:41:51.011Z",
        "emailAddress": "atrivedi@imsa.edu",
        "firstName": "Ayan",
        "lastName": "Trivedi",
        "hall": 1504,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi! My name is Ayan, and some things about me are that I like hanging out with my friends, playing volleyball, and listening to music. In my future, I hope to go to college for pre-med and pursue a career in medicine.",
        "mathcore": "MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Organic Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125290,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T06:41:55.337Z",
        "emailAddress": "adas1@imsa.edu",
        "firstName": "Aahana",
        "lastName": "Das",
        "hall": 1502,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey! I am Aahana! I love everything related to biology, art, and Netflix :)))",
        "mathcore": "MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125253,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-02-01T07:04:01.332Z",
        "emailAddress": "schatterjee@imsa.edu",
        "firstName": "Shatakshi",
        "lastName": "Chatterjee",
        "hall": 1502,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi! My name is Shatakshi, and I am a junior at IMSA! I am passionate about traveling, singing, helping others, taking risks, trying new things, and challenging myself with my classes and commitments. Around campus, I'm a Peer Tutor, RSL, LEAD Facilitator, Student Ambassador, and I take part in Robotics and STEMbassadors.",
        "mathcore": "MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "SI Physics",
        "language": "German I",
        "otherScience": "None, MSI",
        "anyOtherCoursesNotListedAbove": "SAT Prep",
        "id": 125030,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T07:17:59.504Z",
        "emailAddress": "nlaud@imsa.edu",
        "firstName": "Nathan",
        "lastName": "Laud",
        "hall": 1504,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm mostly interested in all things CS, particularly ML. I'm also interested in math and certain sciences. ",
        "mathcore": "MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Physics: Sound and Light",
        "language": "Mandarin I",
        "otherScience": "MSI",
        "id": 125116,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T07:41:25.415Z",
        "emailAddress": "cjenks@imsa.edu",
        "firstName": "Katie ",
        "lastName": "Jenks",
        "hall": 1507,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I go to IMSA. I am a peer tutor.",
        "mathcore": "MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "Statistics",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "Engineering, Computational Science",
        "id": 124282,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-14T15:32:14.456Z",
        "emailAddress": "ahan@imsa.edu",
        "firstName": "Albert",
        "lastName": "Han",
        "hall": 1504,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I like math and physics. ",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "MVC, Intro to Proofs, Modern Geometries, Number Theory, Theory of Analysis, Linear Algebra, Abstract Algebra",
        "cs": "CSI",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Organic Chemistry, Environmental Chemistry",
        "physics": "SI Physics, Physics C: Mechanics, Physics C: E&M, Modern Physics",
        "language": "None",
        "otherScience": "None",
        "id": 124077,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-14T15:50:13.443Z",
        "emailAddress": "gziemer@imsa.edu",
        "firstName": "Greenley ",
        "lastName": "Ziemer",
        "hall": 1507,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm Greenley and I'm a junior in 1507. I really enjoy reading and playing Dungeons and Dragons in my free time. My favorite subjects is bio, and I'm hoping to double up on bio classes next school year.",
        "mathcore": "None",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125241,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T17:53:27.636Z",
        "emailAddress": "apashupati1@imsa.edu",
        "firstName": "Advayth",
        "lastName": "Pashupati",
        "hall": 1503,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Advayth, but I go by Adi. I’m a CS/math major, but I love the other subjects too. I also like reading, table tennis, and Super Smash Bros.",
        "mathcore": "MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "Intro to Proofs",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "SI Physics",
        "language": "French I",
        "otherScience": "Engineering",
        "id": 125161,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-14T17:59:05.968Z",
        "emailAddress": "glu1@imsa.edu",
        "firstName": "George",
        "lastName": "Lu",
        "hall": 1503,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "i do math",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "MVC, Intro to Proofs, Statistics, Problem Solving, Theory of Analysis, Linear Algebra",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "French I, French II",
        "otherScience": "None",
        "id": 124120,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-14T19:22:08.333Z",
        "emailAddress": "vtiruvannamalai@imsa.edu",
        "firstName": "Vignesh ",
        "lastName": "Tiruvannamalai ",
        "hall": 1504,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hello! I'm Vignesh and I'm a senior. My favorite subject is chemistry but I tutor a variety of math, science, and language classes. Outside the classroom, I'm a cross country and track runner, and you can very often find me outside! Feel free to reach out to me on Messenger if you'd like some tutoring help!",
        "mathcore": "MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "None",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "I can also help with English and history classes because I am a writing center tutor!",
        "id": 124219,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-14T20:16:26.794Z",
        "emailAddress": "kkonda@imsa.edu",
        "firstName": "Krish",
        "lastName": "Konda",
        "hall": 1507,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi my name is Krish, and I like to code and play games. I also play the piano and do math sometimes.",
        "mathcore": "MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "Intro to Proofs",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Physics C: Mechanics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "AP CSP and CSA, and AP Music Theory",
        "id": 125109,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-15T17:42:51.554Z",
        "emailAddress": "vjoshi@imsa.edu",
        "firstName": "Vedanti",
        "lastName": "Joshi",
        "hall": 1502,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hello, I’m Vedanti and a junior living in 1502 this year! I’m pretty passionate about math, but I still do love tutoring SI physics and some other random things. ",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I",
        "moreMath": "Statistics",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125094,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-15T19:13:52.313Z",
        "emailAddress": "elendi@imsa.edu",
        "firstName": "Emerald",
        "lastName": "Lendi",
        "hall": 1501,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm a senior who's somehow not burnt out yet. I love working with underclassmen, and I am a die hard cat person.",
        "mathcore": "MI III, MI IV",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems, Biology of Behavior",
        "chemistry": "SI Chemistry, Biochemistry",
        "physics": "SI Physics, Physics: Sound and Light",
        "language": "Mandarin I, Mandarin II",
        "otherScience": "MSI",
        "id": 124296,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-16T04:43:59.574Z",
        "emailAddress": "ssheikh@imsa.edu",
        "firstName": "Saad",
        "lastName": "Sheikh",
        "hall": 1505,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm Saad, a junior from 1505 C wing. Feel free to contact me with any questions, and I look forward to helping you!",
        "mathcore": "MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125286,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-17T15:20:33.827Z",
        "emailAddress": "jchintha@imsa.edu",
        "firstName": "Jediael",
        "lastName": "Chintha",
        "hall": 1507,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "HI! I'm Jediael, a current junior who lives in 07 C-Wing. A cool thing about me is that I like to read books. ",
        "mathcore": "MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None, SI Physics",
        "language": "French I",
        "otherScience": "MSI",
        "id": 125304,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-17T22:47:10.797Z",
        "emailAddress": "mkannan@imsa.edu",
        "firstName": "Maya",
        "lastName": "Kannan",
        "hall": 1502,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I’m Maya and I live in 1502 Dwing. I enjoy dancing and playing sports. My favorite subject is math and through the Peer Tutor program, I hope to develop my fellow peers’ interests in this subject as well.",
        "mathcore": "MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "None",
        "language": "None",
        "otherScience": "None",
        "id": 125096,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-18T03:31:15.092Z",
        "emailAddress": "lnagumalli@imsa.edu",
        "firstName": "Laasya",
        "lastName": "Nagumalli",
        "hall": 1502,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Heyo! My name is Laasya, and I love baking, bunnies, pink, winged eyeliner, and musical theatre. You can often find me in the math office or the 02 hall commons, and I'm very excited to be a peer tutor this semester!!! :D",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "Statistics, Linear Algebra",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics, Physics C: Mechanics, Modern Physics",
        "language": "Mandarin I, Mandarin II",
        "otherScience": "MSI",
        "id": 124144,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-18T04:13:35.785Z",
        "emailAddress": "ahaveliwala@imsa.edu",
        "firstName": "Adam",
        "lastName": "Haveliwala",
        "hall": 1504,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm a junior who goes by he/him pronouns. I am a tutor for MI3, Si Chem, and other various organization skills. I like playing board games and watching TV. ",
        "mathcore": "BC I",
        "moreMath": "Statistics",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "Medicinal Chemistry",
        "physics": "None",
        "language": "Spanish III",
        "otherScience": "None",
        "id": 125262,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-18T22:41:05.018Z",
        "emailAddress": "sdulam@imsa.edu",
        "firstName": "Shrikar",
        "lastName": "Dulam",
        "hall": 1504,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi y'all, I'm Shrikar! I love playing volleyball and listening to music, and I'll be happy to help anyone out. I'm usually in the math center so stop by if you need anything!!!",
        "mathcore": "MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "Intro to Proofs",
        "cs": "CSI, OOP, Web Technologies",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics, Modern Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125049,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-19T21:45:41.356Z",
        "emailAddress": "npaulson@imsa.edu",
        "firstName": "Naomi",
        "lastName": "Paulson",
        "hall": 1506,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I’m a junior living in 06 and I’m always willing to help people out! My hours are Tuesday from 7:00-9:00 pm and Thursday from 7:00-8:00 pm! Please swing by if you need any help!",
        "mathcore": "MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "Mandarin I",
        "otherScience": "None",
        "id": 125165,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T05:41:47.475Z",
        "emailAddress": "jblankenship@imsa.edu",
        "firstName": "Jaden",
        "lastName": "Blankenship",
        "hall": 1503,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey, my name is Jaden! I can help you with just about anything biology-related and any MI-course. Outside of tutoring, I enjoy running track and watching anime.",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "None",
        "biology": "Advanced Biological Systems, Cancer Biology",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "French I, French II, French III",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "amstud",
        "id": 125018,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T05:46:20.774Z",
        "emailAddress": "jmu@imsa.edu",
        "firstName": "Joshua",
        "lastName": "Mu",
        "hall": 1503,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I like learning chemistry and running. And also sleeping.",
        "mathcore": "BC I, BC II, BC III",
        "moreMath": "Linear Algebra",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry, Advanced Chemistry, Organic Chemistry",
        "physics": "SI Physics, Physics C: Mechanics",
        "language": "Spanish II, Spanish III, Spanish IV",
        "otherScience": "MSI",
        "id": 125144,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T07:34:14.910Z",
        "emailAddress": "jwomack@imsa.edu",
        "firstName": "Jaxon",
        "lastName": "Womack",
        "hall": 1504,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey, I'm Jaxon. I'm from a town on the far west border of Illinois, and I'd love to share my skills with those who would benefit from them. Please ask me anything, I'm an RSL so I can answer non-academic questions too. ",
        "mathcore": "MI II, MI III, MI IV, BC I",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "None, SI Chemistry",
        "physics": "None, SI Physics",
        "language": "French I",
        "otherScience": "None",
        "anyOtherCoursesNotListedAbove": "CAD softwares, computer IT help",
        "id": 125228,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T18:48:20.102Z",
        "emailAddress": "kmalladi@imsa.edu",
        "firstName": "Sadkrith",
        "lastName": "Malladi",
        "hall": 1505,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hello, my name is Sadkrith and I live in 1505 B-wing. I like to play chess, read, write, and listen to music. I enjoy learning almost anything and I am excited to try my hand at teaching. ",
        "mathcore": "BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry, Advanced Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III, Spanish IV, Spanish V",
        "otherScience": "MSI",
        "id": 125126,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-20T21:36:47.292Z",
        "emailAddress": "kuppal@imsa.edu",
        "firstName": "Kavya",
        "lastName": "Uppal",
        "hall": 1502,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hey guys! I’m Kavya, and I’m a junior who lives in 1502 A wing. Along with regular subjects, I can also help you with public speaking, speech/presentation writing, and interview and presentation skills, so always feel free to stop by for those :))",
        "mathcore": "Geometry, MI I/II, MI II, MI III, BC I",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125315,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-21T03:57:58.026Z",
        "emailAddress": "etrone@imsa.edu",
        "firstName": "Evan",
        "lastName": "Trone",
        "hall": 1507,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "1507 Hall Peer Tutor, feel free to come to me for help or if you have any questions!",
        "mathcore": "MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "None",
        "id": 125214,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-21T23:00:37.428Z",
        "emailAddress": "mpark2@imsa.edu",
        "firstName": "Mia",
        "lastName": "Park",
        "hall": 1503,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I enjoy reading manga, drawing, and eating good food. My favorite subject is chemistry, and my favorite manga series is Kaiju No. 8!",
        "mathcore": "MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "None",
        "otherScience": "None",
        "id": 125311,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T01:38:22.116Z",
        "emailAddress": "akatson@imsa.edu",
        "firstName": "Andrew",
        "lastName": "Katson",
        "hall": 1504,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi! I'm Andrew, a peer tutor from 1504! My academic interests include mathematics, physics, nutrition, and sports science. Feel free to reach out over messenger if you need anything!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "MVC, Intro to Proofs, Statistics, Discrete Mathematics",
        "cs": "None",
        "biology": "Advanced Biological Systems",
        "chemistry": "None",
        "physics": "SI Physics, Physics C: Mechanics",
        "language": "None",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "Moving and Learning",
        "id": 125100,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T05:00:56.616Z",
        "emailAddress": "mwolkowitz@imsa.edu",
        "firstName": "Mila",
        "lastName": "Wolkowitz ",
        "hall": 1501,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Mila and I will have a bigger variety classes to help with after this sem. I can also help with essays. I hope to help soon! ",
        "mathcore": "MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Organic Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III, Spanish IV",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "LE, Awrap",
        "id": 125227,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T06:03:43.826Z",
        "emailAddress": "cpark@imsa.edu",
        "firstName": "Chad",
        "lastName": "Park",
        "hall": 1507,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, my name is Chad and I am a junior. I enjoy math, physics, tennis, music, and more!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Modern Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI",
        "id": 125160,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T06:08:19.310Z",
        "emailAddress": "akumar4@imsa.edu",
        "firstName": "Aditya ",
        "lastName": "Kumar",
        "hall": 1507,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "\nI'm Aditya, a food enthusiast who enjoys the thrill of volleyball and the escape of a good book. I like to think of myself as a nice person, bringing positivity to every encounter.",
        "mathcore": "Geometry, MI I/II, MI II, MI III",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Mandarin I",
        "otherScience": "MSI, Engineering",
        "id": 125112,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T16:14:16.966Z",
        "emailAddress": "cobriendull@imsa.edu",
        "firstName": "Claire",
        "lastName": "O'Brien-Dull",
        "hall": 1507,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I'm Claire, a senior in 07 A-wing. I love math and physics, which I am thrilled to tutor, but I can help with other subjects too!",
        "mathcore": "MI IV, BC I, BC II, BC III",
        "moreMath": "Linear Algebra",
        "cs": "None",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Physics: Sound and Light, Physics C: Mechanics, Physics C: E&M, Modern Physics",
        "language": "None",
        "otherScience": "Computational Science",
        "id": 124320,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-22T17:54:21.654Z",
        "emailAddress": "swalsh@imsa.edu",
        "firstName": "Stephen",
        "lastName": "Walsh",
        "hall": 1504,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hello, I'm Stephen Walsh, a peer tutor from 1504. I'd be happy to help you with physics, math, and French.",
        "mathcore": "MI IV, BC I, BC II, BC III",
        "moreMath": "MVC, Intro to Proofs, Number Theory, Theory of Analysis, Differential Equations, Linear Algebra",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "None",
        "physics": "SI Physics, Physics C: Mechanics, Physics C: E&M",
        "language": "French II, French III, French IV",
        "otherScience": "None",
        "id": 124227,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-22T23:02:37.107Z",
        "emailAddress": "apham@imsa.edu",
        "firstName": "Anzilina",
        "lastName": "Pham",
        "hall": 1506,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hello! My name is Anzilina and I'm a current junior. I tutor for math and French, but can also help with graphic designs for posters/presentations! ",
        "mathcore": "MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "None",
        "physics": "None",
        "language": "French I, French II",
        "otherScience": "None",
        "id": 125168,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-22T23:54:03.968Z",
        "emailAddress": "rchen1@imsa.edu",
        "firstName": "Richard",
        "lastName": "Chen",
        "hall": 1504,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Richard, and I play tennis and enjoy a multitude of games. My favorite classes currently are E+M, MVC, and diff eq.",
        "mathcore": "BC I, BC II, BC III",
        "moreMath": "None",
        "cs": "OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Physics C: Mechanics, Modern Physics",
        "language": "French II",
        "otherScience": "None",
        "id": 125034,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-23T03:22:53.000Z",
        "emailAddress": "hshah@imsa.edu",
        "firstName": "Haley",
        "lastName": "Shah",
        "hall": 1506,
        "wing": "B",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "In my free time, I like to figure skate and dance. I have a younger brother and have lots of prior experience tutoring my peers. I am always available to help, so feel free to reach out!",
        "mathcore": "MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125190,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-23T06:09:52.483Z",
        "emailAddress": "pobazuaye1@imsa.edu",
        "firstName": "Philip",
        "lastName": "Obazuaye",
        "hall": 1507,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "My name is Philip. I am a junior from 1507 D-wing. I tutor Geometry, MI II and III, SI chem, Sound and Light, Spanish II, and MSI.",
        "mathcore": "Geometry, MI II, MI III",
        "moreMath": "None",
        "cs": "None",
        "biology": "None",
        "chemistry": "None",
        "physics": "Physics: Sound and Light",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125153,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-24T15:55:23.407Z",
        "emailAddress": "mbalasubramanian@imsa.edu",
        "firstName": "Manasa",
        "lastName": "Balasubramanian",
        "hall": 1506,
        "wing": "D",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "Hi, I'm Manasa! I'm a senior this year and am really happy to be a peer tutor for this semester! I'm really interested in the sciences and am good at some math subjects. If you have any questions, please come and ask me!",
        "mathcore": "MI II, MI III",
        "moreMath": "Statistics",
        "cs": "None",
        "biology": "Advanced Biological Systems, Cancer Biology, Biology of Behavior",
        "chemistry": "SI Chemistry, Organic Chemistry",
        "physics": "SI Physics",
        "language": "French I, French II",
        "otherScience": "Engineering",
        "id": 124014,
        "graduationYear": 2024
    },
    {
        "timestamp": "2024-01-29T07:35:05.372Z",
        "emailAddress": "jkim5@imsa.edu",
        "firstName": "Jongwoo ",
        "lastName": "Kim",
        "hall": 1503,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I enjoy playing volleyball and swimming. You can find me in the hall commons most of the times after ten check besides my regular hours!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV, BC I, BC II",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "Advanced Biological Systems",
        "chemistry": "SI Chemistry, Organic Chemistry, Medicinal Chemistry",
        "physics": "SI Physics",
        "language": "Spanish II, Spanish III",
        "otherScience": "MSI",
        "anyOtherCoursesNotListedAbove": "Moving and Learning",
        "id": 125103,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-01-31T22:39:01.725Z",
        "emailAddress": "kkranthi@imsa.edu",
        "firstName": "Khushi",
        "lastName": "Kranthi",
        "hall": 1507,
        "wing": "A",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am a Junior in 1507 who teaches various subjects, feel free to come to me at any time, even when I am not technically tutoring. I would love to help!",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Physics: Sound and Light",
        "language": "Mandarin I, Mandarin II",
        "otherScience": "MSI, Engineering",
        "id": 125272,
        "graduationYear": 2025
    },
    {
        "timestamp": "2024-02-01T22:56:07.956Z",
        "emailAddress": "ylakhani@imsa.edu",
        "firstName": "Yaalini",
        "lastName": "Lakhani",
        "hall": 1507,
        "wing": "C",
        "aboutMeThisDoesntHaveToBeLongMaybeJustAQuick23Sentences": "I am a current junior at IMSA. I love to listen to music and read. ",
        "mathcore": "Geometry, MI I/II, MI II, MI III, MI IV",
        "moreMath": "None",
        "cs": "CSI, OOP",
        "biology": "None",
        "chemistry": "SI Chemistry",
        "physics": "SI Physics, Modern Physics",
        "language": "Spanish II",
        "otherScience": "MSI",
        "id": 125309,
        "graduationYear": 2025
    }
]

transform(d)